### ISSUE TITLE
[1st tab] Robot state info

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/rosee_gui#3]
such as joint position, velocities...

**Comment by torydebra** [comment]
![guinew](https://user-images.githubusercontent.com/26459008/81083663-265d4580-8ef5-11ea-95f1-2f34b2ca15fb.png)

This is the idea. I want to use the checkboxes below the table to show only some column and row.
For the not actuated joint, we need this info that now GUI does not have. 
I see 2 options for that:
- Add a service with joint name and actuated joint name
- A sort of "hack": take this info from topics. The actuated joints can be taken from joint_command topic (the topic which rosee core is the publisher) and all joints names can be taken from joint_states (where OR joint publisher publishes (no gazebo) OR gazebo plugin (when gazebo used))
- None of those because these checkboxes are not so interesting to have.

**Comment by liesrock** [comment]
The direction is to follow @alaurenzi GUI for robot monitoring for the robot state as @torydebra is already doing!

**Comment by alaurenzi** [comment]
If possible, I suggest to avoid duplicating the GUI code. If the `robot_monitoring` GUI proves not to be modular enough, I can help on that provided some API requirements

**Comment by liesrock** [comment]
Basically the state of the hand joints will be handle by a separate tab of the main GUI from my prospective: they have some components in common, but the hand GUI will also have the grasping action to command and can work in a standalone fashion.

**Comment by liesrock** [comment]
We can think to have a design meeting together anyhow to discuss about the above.

**Comment by torydebra** [comment]
Yes maybe a meeting is more convenient than discussing here.
For now what I thought:
- To put some joint states toghether with the action, because I like to see the joints states while the action is running, instead have to switch to another tab.
- I see with these states the window starts to be too filled. I was thinking to have a different layout for action: one single "square" for all actions. Maybe we can have both layouts in different tabs.
- Won't we use rqt ? It has already something like graph. We can also think to integrate the action GUI into rqt, as widget...
- We can also think to add the @alaurenzi robot_monitoring as additional tab or something like that...

**Comment by torydebra** [comment]
Regarding this:
> 
> This is the idea. I want to use the checkboxes below the table to show only some column and row.
> For the not actuated joint, we need this info that now GUI does not have.
> I see 2 options for that:
> 
> * Add a service with joint name and actuated joint name
> * A sort of "hack": take this info from topics. The actuated joints can be taken from joint_command topic (the topic which rosee core is the publisher) and all joints names can be taken from joint_states (where OR joint publisher publishes (no gazebo) OR gazebo plugin (when gazebo used))
> * None of those because these checkboxes are not so interesting to have.

I proceeded taking joint name from ros param (robot_description and robot_description_semantic), ie from urdf and srdf file. Probably this is the better solution. 
Now the checkboxes hide the rows and columns as intended, plus I added color to distinguish the three types of joint (actuated, passive, mimic)

![gui](https://user-images.githubusercontent.com/26459008/82915886-9d747f80-9f71-11ea-8fdc-04adc949d012.png)

**Comment by torydebra** [comment]
![guiiii](https://user-images.githubusercontent.com/26459008/88037090-c0bc4500-cb44-11ea-9631-c60d6e5ef6a4.png)

final state of the first tab. Colors are removed but different tables are used for actuated, mimic and passive
