### ISSUE TITLE
[2nd tab] Layout ideas from robot monitoring 

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/rosee_gui#5]
I would leave some essential info about joint states in the first tab as in issue #3 
I would use this second tab for more "monitoring", following (and/or using) robot_monitoring gui of @alaurenzi : 
![81796240-751a6900-950d-11ea-9774-a7ccbfa949fa](https://user-images.githubusercontent.com/26459008/82573860-966efb00-9b86-11ea-909b-1f4e0aa15494.png)

I would change this a bit:
- On the left, let have the possibility to show more than one parameter of all joints (eg joint pos and vel). We should have enough space if no mimic joint are displayed.
- Like in issue #3, have the possibility to not show the mimic joints info (that probably will be neither available)
- Substitute the "orange" widget with a new rosee action widget, where any action can be commanded (like in the first tab, but here not showing all the action at the same time). 
  This because: 
  - so I can "monitor" and plotting a lot of things while commanding.
  - the original orange rectangle should be useless for rosee: if we want to control directly the joint
  we can simply use the joint_state_publisher right?

**Comment by torydebra** [comment]
Work so far
![2ndtab](https://user-images.githubusercontent.com/26459008/82688909-f97d9200-9c59-11ea-9603-576d2a61fc49.png)

**Comment by liesrock** [comment]
The idea to command the hand is just to use grasping primitives, that I expect are going to be found in the "Action" tab.
I like the GUI, to test it on my pc which branch should I use?

**Comment by torydebra** [comment]
All the new functionalities are in the _devel2_ branch.
Please be sure to have qt >5.9 (qt 5.12 is good). Relative issue about it #4 
I have also some problems with `#include` so depending where you install qt 5.12 you may need to change something accordingly (#7 )

**Comment by torydebra** [comment]
I close this, the devel2 branch has reached a nice final state
