### ISSUE TITLE
[2nd tab] Blue "loading" bars for some joint position

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/rosee_gui#6]
Hi @Alaurenzi,
I brutally copied your robot_monitoring and adapted it. I have some issue I need to solve, but maybe you have an idea
as you can see, for some joints the position is not printed in the bar, and the "loading blue" bars remains. The message should arrive correctly, because for some joints position is correct, I can also print in the plot.
![2ndtab](https://user-images.githubusercontent.com/26459008/82679386-32fad100-9c4b-11ea-968a-9679eb7e68ea.png)

**Comment by torydebra** [comment]
Found the problem!
The setRange() of a progress bar takes only integers. So the qmax and qmin (that are double) are converted to integers when passed to setRange, and if the max is <1, the progress bar will have 0 min and 0 max, hence the "undefined" behaviour. I solved with this hack:
~~~c++
auto wid = barplot_wid->wid_map.at(msg->name[i]);

//set range want only integer... so I multiply by 100 everything,
// but the text will be written correct.
// if we use getValue(), we will need to divide it by 100
wid->setValue(msg->position[i]*100, msg->position[i]);
double qmin = _urdf->getJoint(msg->name[i])->limits->lower;
double qmax = _urdf->getJoint(msg->name[i])->limits->upper;
wid->setRange(qmin*100, qmax*100);
~~~

This keep the visually looking bar that moves amonge the two limits, but also show the printed value correctly.

**Comment by alaurenzi** [comment]
Nice catch!
